In [2]:
import pandas as pd

In [3]:
dataset=pd.read_csv(r'https://github.com/YBI-Foundation/Dataset/raw/main/Financial%20Market%20News.csv',encoding='ISO.8859.1')

In [4]:
dataset.head()

Date  Label                                             News 1  \
0  01-01-2010      0           McIlroy's men catch cold from Gudjonsson   
1  02-01-2010      0               Warning from history points to crash   
2  03-01-2010      0      Comment: Why Israel's peaceniks feel betrayed   
3  04-01-2010      1             £750,000-a-goal Weah aims parting shot   
4  05-01-2010      1  Leeds arrive in Turkey to the silence of the fans   

                                       News 2  \
0                       Obituary: Brian Walsh   
1              Investors flee to dollar haven   
2  Court deals blow to seizure of drug assets   
3            Newcastle pay for Fletcher years   
4     One woman's vision offers loan lifeline   

                                            News 3  \
0       Workplace blues leave employers in the red   
1                      Banks and tobacco in favour   
2                       An ideal target for spooks   
3  Brown sent to the stands for Scotland qualifier   
4          Working Lives: How world leaders worked   

                                        News 4  \
0                     Classical review: Rattle   
1                        Review: Llama Farmers   
2  World steps between two sides intent on war   
3         Tourists wary of breaking new ground   
4           Working Lives: Tricks of the trade   

                                              News 5  \
0                     Dance review: Merce Cunningham   
1                       War jitters lead to sell-off   
2                       What the region's papers say   
3              Canary Wharf climbs into the FTSE 100   
4  Working Lives: six-hour days, long lunches and...   

                                         News 6  \
0  Genetic tests to be used in setting premiums   
1                    Your not-so-secret history   
2           Comment: Fear and rage in Palestine   
3                           Review: Bill Bailey   
4                        Pop review: We Love UK   

                                          News 7  \
0                        Opera review: La Bohème   
1                  Review: The Northern Sinfonia   
2  Poverty and resentment fuels Palestinian fury   
3                              Review: Classical   
4               World music review: Marisa Monte   

                                        News 8  ...  \
0                   Pop review: Britney Spears  ...   
1                             Review: Hysteria  ...   
2  Republican feud fear as dissident is killed  ...   
3              Review: New Contemporaries 2000  ...   
4             Art review:  Hollingsworth/Heyer  ...   

                                News 16                              News 17  \
0                 Finland 0 - 0 England                   Healy a marked man   
1  Why Wenger will stick to his Gunners  Out of luck England hit rock bottom   
2             FTSE goes upwardly mobile             At this price?  BP Amoco   
3         More cash on way for counties      Cairns carries Kiwis to victory   
4          Duisenberg in double trouble           Pru to cut pension charges   

                                             News 18  \
0                     Happy birthday Harpers & Queen   
1                         Wilkinson out of his depth   
2                                            Go fish   
3  Year of Blanchflower's flourish when Spurs sto...   
4                            Art review: Paul Graham   

                                             News 19  \
0  Win unlimited access to the Raindance film fes...   
1                   Kinsella sparks Irish power play   
2         Bosnian Serb blows himself up to evade law   
3      New direct approach brings only pay-per-blues   
4               Shearer shot sparks Boro humiliation   

                                             News 20  \
0  Labour pledges £800m to bridge north-south divide   
1                    Brown banished as Scots rebound   
2                       Or

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4101 entries, 0 to 4100
Data columns (total 27 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Date     4101 non-null   object
 1   Label    4101 non-null   int64 
 2   News 1   4101 non-null   object
 3   News 2   4101 non-null   object
 4   News 3   4101 non-null   object
 5   News 4   4101 non-null   object
 6   News 5   4101 non-null   object
 7   News 6   4101 non-null   object
 8   News 7   4101 non-null   object
 9   News 8   4101 non-null   object
 10  News 9   4101 non-null   object
 11  News 10  4101 non-null   object
 12  News 11  4101 non-null   object
 13  News 12  4101 non-null   object
 14  News 13  4101 non-null   object
 15  News 14  4101 non-null   object
 16  News 15  4101 non-null   object
 17  News 16  4101 non-null   object
 18  News 17  4101 non-null   object
 19  News 18  4101 non-null   object
 20  News 19  4101 non-null   object
 21  News 20  4101 non-null   object
 22  

In [6]:
dataset.describe()

Label
count  4101.000000
mean      0.528164
std       0.499267
min       0.000000
25%       0.000000
50%       1.000000
75%       1.000000
max       1.000000

In [7]:
dataset.columns


Index(['Date', 'Label', 'News 1', 'News 2', 'News 3', 'News 4', 'News 5',
       'News 6', 'News 7', 'News 8', 'News 9', 'News 10', 'News 11', 'News 12',
       'News 13', 'News 14', 'News 15', 'News 16', 'News 17', 'News 18',
       'News 19', 'News 20', 'News 21', 'News 22', 'News 23', 'News 24',
       'News 25'],
      dtype='object')

In [7]:
dataset.index

RangeIndex(start=0, stop=4101, step=1)

In [8]:
news=[]
for row in range(0,len(dataset.index)):
  news.append(' '.join(str(x) for x in dataset.iloc[row,2:27]))



In [9]:
X=news
type(X)

list

In [10]:
news[0]

"McIlroy's men catch cold from Gudjonsson Obituary: Brian Walsh Workplace blues leave employers in the red Classical review: Rattle Dance review: Merce Cunningham Genetic tests to be used in setting premiums Opera review: La Bohème Pop review: Britney Spears Theatre review: The Circle Wales face a fraught night Under-21  round-up Smith off to blot his copybook Finns taking the mickey Praise wasted as Brown studies injury options Ireland wary of minnows Finland 0 - 0 England Healy a marked man Happy birthday Harpers & Queen Win unlimited access to the Raindance film festival Labour pledges £800m to bridge north-south divide Wales: Lib-Lab pact firm despite resignation Donald Dewar Regenerating homes  regenerates well-being in people Win £100 worth of underwear TV guide: Random views"

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

In [12]:
vectorizer = CountVectorizer(lowercase=True,ngram_range=(1,1))
X=vectorizer.fit_transform(X)

In [24]:
X.shape

(4101, 48527)

In [26]:
X[0]

<1x48527 sparse matrix of type '<class 'numpy.int64'>'
	with 107 stored elements in Compressed Sparse Row format>

In [14]:
Y=dataset['Label']

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y, train_size=0.7, random_state=2529)

In [16]:
# check shape of train and test sample
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((2870, 48527), (1231, 48527), (2870,), (1231,))

In [27]:
# Step 5 : select model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=500)

In [62]:
model.fit(X_train,y_train)

LogisticRegression(max_iter=500)

In [63]:
# Step 7 : predict model
y_pred = model.predict(X_test)

In [21]:
# Step 8 : model accuracy
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [65]:
confusion_matrix(y_test,y_pred)

array([[279, 315],
       [280, 357]])

In [66]:
accuracy_score(y_test,y_pred)

0.5166531275385865

In [67]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.50      0.47      0.48       594
           1       0.53      0.56      0.55       637

    accuracy                           0.52      1231
   macro avg       0.52      0.52      0.51      1231
weighted avg       0.52      0.52      0.52      1231



In [68]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()

In [69]:
model.fit(X_train,y_train)

RandomForestClassifier()

In [70]:
# Step 7 : predict model
y_pred = model.predict(X_test)

In [71]:
confusion_matrix(y_test,y_pred)

array([[165, 429],
       [150, 487]])

In [72]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.52      0.28      0.36       594
           1       0.53      0.76      0.63       637

    accuracy                           0.53      1231
   macro avg       0.53      0.52      0.50      1231
weighted avg       0.53      0.53      0.50      1231



In [18]:
from sklearn.svm import SVC # "Support vector classifier"  
classifier = SVC(kernel='linear', random_state=0)  
classifier.fit(X_train,y_train) 

SVC(kernel='linear', random_state=0)

In [19]:
# Step 7 : predict model
y_pred = classifier.predict(X_test)

In [22]:
confusion_matrix(y_test,y_pred)

array([[284, 310],
       [291, 346]])

In [23]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.49      0.48      0.49       594
           1       0.53      0.54      0.54       637

    accuracy                           0.51      1231
   macro avg       0.51      0.51      0.51      1231
weighted avg       0.51      0.51      0.51      1231

